### ISSUE TITLE
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

### ISSUE THREAD

**Issue by windowshopr** [epifab/pypoker#14]
Python 3.11, Flask==2.2.2, Windows 10

After firing up the server and joining a room, get this error in the server log:

```
127.0.0.1 - - [19/Nov/2022 03:04:13] "GET /poker/texas-holdem HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
                      ^^^^^^^^^^^^^^^
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 622, in match
    raise WebsocketMismatch() from None
werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by orfey7** [comment]
> Python 3.11, Flask==2.2.2, Windows 10
> 
> After firing up the server and joining a room, get this error in the server log:
> 
> ```
> 127.0.0.1 - - [19/Nov/2022 03:04:13] "GET /poker/texas-holdem HTTP/1.1" 500 -
> Error on request:
> Traceback (most recent call last):
>   File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
>     execute(self.server.app)
>   File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\serving.py", line 322, in execute
>     application_iter = app(environ, start_response)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2548, in __call__
>     return self.wsgi_app(environ, start_response)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_sockets.py", line 40, in __call__
>     handler, values = adapter.match()
>                       ^^^^^^^^^^^^^^^
>   File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 622, in match
>     raise WebsocketMismatch() from None
> werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
> ```

I faced the same problem(
Only the table and the nickname that you entered appear on the page, without the ability to play
Did you solve it?

**Comment by Nacriema** [comment]
Hi, 

I faced the same problem. Please change the content inside `requirements.txt` to:

```
Flask-Sockets==0.2.1
gunicorn==20.0.4
redis==3.5.3
Flask==1.1.4
Werkzeug==1.0.1
markupsafe==2.0.1
```

**Comment by danarteaga** [comment]
This will fix it without having to update the libraries:

`def add_url_rule(self, rule, _, f, **options):
    self.url_map.add(flask_sockets.Rule(rule, endpoint=f, websocket=True))
flask_sockets.Sockets.add_url_rule = add_url_rule`
